# delegate to main makefile with the right target

.PHONY: all clean distclean

all:
	@$(MAKE) -C ../../ runtime

clean:
	@$(MAKE) -C ../../ runtime-clean

distclean:
	@$(MAKE) -C ../../ runtime-distclean
