# ==========================
# File lists
# ==========================

RTM_DIR := src/runtime

RTM_SOURCE_DIRS := src/runtime
RTM_SOURCE_FILES := $(foreach dir,$(RTM_SOURCE_DIRS),$(wildcard $(dir)/*.c))

RTM_OBJECTS = $(RTM_SOURCE_FILES:.c=.o)
RTM_DEPENDENCIES = $(RTM_SOURCE_FILES:.c=.d)

RTM_LDFLAGS = -shared
RTM_LIBS = $(LIBSVM_TARGET_LIB)

# ==========================
# System dependent
# ==========================

ifeq ($(PLATFORM),MinGW)
  RTM_LIB_NAME := sept-runtime.dll
else
  RTM_LIB_NAME := sept-runtime.so
endif
RTM_TARGET_LIB := $(MODULES_DIR)/$(RTM_LIB_NAME)

# ==========================
# Target library
# ==========================

.PHONY: runtime runtime-clean runtime-distclean

runtime: $(RTM_TARGET_LIB)

$(RTM_TARGET_LIB): $(LIBSVM_TARGET_LIB) $(RTM_LIBS) $(RTM_OBJECTS) | $(MODULES_DIR)
	$(CC) $(RTM_LDFLAGS) $(RTM_OBJECTS) $(RTM_LIBS) -o$@

# ==========================
# Cleaning
# ==========================

runtime-clean:
	$(RM) $(call fix_paths,$(RTM_TARGET_LIB) $(RTM_OBJECTS))

runtime-distclean: runtime-clean
	$(RM) $(call fix_paths,$(RTM_DEPENDENCIES))

# ==========================
# Autogenerated dependencies
# ==========================

# cleaning does not need dependencies
ifeq (,$(findstring clean,$(MAKECMDGOALS)))
    -include $(RTM_DEPENDENCIES)
endif
