# ==========================
# Toolchain
# ==========================

CC = gcc
RM = del
CFLAGS = -g -Wall -Wfatal-errors -DSEP_LOGGING_ENABLED
LDFLAGS = 

# ==========================
# Adapt file paths for use with Windows commands
# ==========================

OBJECT_FILES = $(subst /,\,$(OBJECTS))
DEP_FILES = $(subst /,\,$(DEPS))
