# delegate to main makefile with the right target

.PHONY: all clean distclean

all:
	@$(MAKE) -C ../../ interpreter

clean:
	@$(MAKE) -C ../../ interpreter-clean

distclean:
	@$(MAKE) -C ../../ interpreter-distclean
