# ==========================
# File lists
# ==========================

LIBSVM_DIR := src/libseptvm

LIBSVM_SOURCE_DIRS := src/libseptvm/common \
  src/libseptvm/io \
  src/libseptvm/runtime \
  src/libseptvm/vm \
  src/libseptvm

LIBSVM_SOURCE_FILES := $(foreach dir,$(LIBSVM_SOURCE_DIRS),$(wildcard $(dir)/*.c))
LIBSVM_LIBRARY_HEADER := src/libseptvm/septvm.h

LIBSVM_OBJECTS = $(LIBSVM_SOURCE_FILES:.c=.o)
LIBSVM_DEPENDENCIES = $(LIBSVM_SOURCE_FILES:.c=.d)

# ==========================
# System dependent parts
# ==========================

LIBSVM_TARGET_LIB := $(LIB_DIR)/libseptvm.a

# ==========================
# Executable
# ==========================

.PHONY: libseptvm libseptvm-clean libseptvm-distclean

libseptvm: $(LIBSVM_TARGET_LIB)

$(LIBSVM_TARGET_LIB): $(LIBSVM_OBJECTS) | $(LIB_DIR)
	-$(RM) $@
	$(AR) rcs $@ $(LIBSVM_OBJECTS)

# ==========================
# Cleaning
# ==========================

libseptvm-clean:
	$(RM) $(call fix_paths,$(LIBSVM_TARGET_LIB) $(LIBSVM_OBJECTS))

libseptvm-distclean: libseptvm-clean
	$(RM) $(call fix_paths,$(LIBSVM_DEPENDENCIES))

# ==========================
# Autogenerated dependencies
# ==========================

# cleaning does not need dependencies
ifeq (,$(findstring clean,$(MAKECMDGOALS)))
    -include $(LIBSVM_DEPENDENCIES)
endif
